from tkinter import *
window = Tk()
window.state('zoomed')

# creating File menu
menu_bar = Menu()
file = Menu(menu_bar, tearoff=0)
menu_bar.add_cascade(label='File', menu=file)
file.add_command(label='New File', accelerator='Ctrl+N')
file.add_command(label='New Window', accelerator='Ctrl+Shift+N')
file.add_separator()
file.add_command(label='Open File...', accelerator='Ctrl+O')
file.add_command(label='Open Folder', accelerator='Ctrl+K Ctrl+O')
file.add_command(label='Open Workspace from File...')
file.add_command(label='Open Recent')
file.add_separator()
file.add_command(label='Add Folder to Workspace')
file.add_command(label='Save Workspace As...')
file.add_command(label='Duplicate Workspace')
file.add_separator()
file.add_command(label='Save', accelerator='Ctrl+S')
file.add_command(label='Save As...', accelerator='Ctrl+Shift+S')
file.add_command(label='Save All', accelerator='Ctrl+K S')
file.add_separator()
file.add_command(label='Auto Save')
# sub menu create
sub_menu = Menu(menu_bar, tearoff=0)
file.add_cascade(label='preference', menu=sub_menu)
sub_menu.add_command(label='Settings', accelerator='Ctrl+,')
sub_menu.add_command(label='Online Services Setting')
sub_menu.add_command(label='Telemetry')
sub_menu.add_command(label='Extensions', accelerator='Ctrl+Shift+X')
sub_menu.add_separator()
sub_menu.add_command(label='Keybord Shortcuts', accelerator='Ctrl+K Ctrl+S')
sub_menu.add_command(label='Migrate Keyboard Shortcuts from...')
sub_menu.add_separator()
sub_menu.add_command(label='User Snippets')
sub_menu.add_separator()
sub_menu.add_command(label='Color Theme', accelerator='Ctrl+K Ctrl+T')
sub_menu.add_command(label='File Icon Theme')
sub_menu.add_command(label='Product Icon Theme')
sub_menu.add_separator()
sub_menu.add_command(label='Turn on Setting Sync...')
file.add_separator()

file.add_command(label='Revert File')
file.add_command(label='Close Editor', accelerator='Ctrl+F4')
file.add_command(label='Close Folder', accelerator='Ctrl+K F')
file.add_command(label='Close Window', accelerator='Alt+F4')
file.add_separator()
file.add_command(label='Exit', command=quit)

#now create Edit menu
edit=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='Edit',menu=edit)
edit.add_command(label='Undo',accelerator='Ctrl+Z')
edit.add_command(label='Redo',accelerator='Ctrl+Y')
edit.add_separator()
edit.add_command(label='Cut',accelerator='Ctrl+X')
edit.add_command(label='Copy',accelerator='Ctrl+C')
edit.add_command(label='Past',accelerator='Ctrl+V')
edit.add_separator()
edit.add_command(label='Find',accelerator='Ctrl+F')
edit.add_command(label='Replace',accelerator='Ctrl+H')
edit.add_separator()
edit.add_command(label='FInd in Files',accelerator='Ctrl+Shift+F')
edit.add_command(label='Replace in Files',accelerator='Ctrl+Shift+H')
edit.add_separator()
edit.add_command(label='Toggle Line Comment',accelerator='Ctrl+/')
edit.add_command(label='Toggle Block Comment',accelerator='Ctrl+Alt+A')
edit.add_command(label='Emmet:Expand abbreviation',accelerator='Tab')

#add selection menu
selection=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='Selection',menu=selection)
selection.add_command(label='Select All',accelerator='Ctrl+A')
selection.add_command(label='Expand Selection',accelerator='Shift+Alt+RightArrow')
selection.add_command(label='Shrink Selection',accelerator='Shift+Alt+LeftArrow')
selection.add_separator()
selection.add_command(label='Copy Line Up',accelerator='Shift+Alt+UpArrow')
selection.add_command(label='Copy Line Down',accelerator='Shift+Alt+DownArrow')
selection.add_command(label='Move Line Up',accelerator='Alt+UpArrow')
selection.add_command(label='Move Line Down',accelerator='Alt+DownArrow')
selection.add_command(label='Duplication Selection')
selection.add_separator()
selection.add_command(label='Add Cursor Above',accelerator='Ctrl+Alt+UpArrow')
selection.add_command(label='Add Cursor Below',accelerator='Ctrl+Alt+DownArrow')
selection.add_command(label='Add Cursor to Line Ends',accelerator='Shift+Alt+I')
selection.add_command(label='ADD Next Occurrence',accelerator='Ctrl+D')
selection.add_command(label='Add Previous Occurrence')
selection.add_command(label='Select All Occurrences',accelerator='Ctrl+Shift+L')
selection.add_separator()
selection.add_command(label='Switch to Ctrl+Click for Multi-Cursor')
selection.add_command(label='Column Selection Mode')

#create view menu
view=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='View',menu=view)
view.add_command(label='Command Palette...',accelerator='Ctrl+Shift+P')
view.add_command(label='Open View...')
view.add_separator()

sub_Appearance=Menu(menu_bar,tearoff=0)
view.add_cascade(label='Appearance',menu=sub_Appearance)
sub_Appearance.add_command(label='Full Screen',accelerator='F11')
sub_Appearance.add_command(label='Zen Mode',accelerator='Ctrl+K Z')
sub_Appearance.add_command(label='Centered Layout')
sub_Appearance.add_separator()
sub_Appearance.add_command(label='Show Menu Bar')
sub_Appearance.add_command(label='Show Side Bar',accelerator='Ctrl+B')
sub_Appearance.add_command(label='Show Status Bar')
sub_Appearance.add_command(label='Show Activity Bar')
sub_Appearance.add_command(label='Show Panel',accelerator='Ctrl+J')
sub_Appearance.add_command(label='Show Editor Area')
sub_Appearance.add_separator()
sub_Appearance.add_command(label='Move Side Bar')
sub_Appearance.add_command(label='Move Panel Left')
sub_Appearance.add_command(label='Move Panel Right')
sub_Appearance.add_separator()
sub_Appearance.add_command(label='Zoom In',accelerator='Ctrl+=')
sub_Appearance.add_command(label='Zoom Out',accelerator='Ctrl+-')
sub_Appearance.add_command(label='Reset Zoom',accelerator='Ctrl+NumPad0')


sub_Edit_Layout=Menu(menu_bar, tearoff=0)
view.add_cascade(label='Editor Layout',menu=sub_Edit_Layout)
sub_Edit_Layout.add_command(label='Split Up')
sub_Edit_Layout.add_command(label='Split Down')
sub_Edit_Layout.add_command(label='Split Left')
sub_Edit_Layout.add_command(label='Split Right')
sub_Edit_Layout.add_separator()
sub_Edit_Layout.add_command(label='Split in Group',accelerator='Ctrl+K Ctrl+Shift+\\')
sub_Edit_Layout.add_separator()
sub_Edit_Layout.add_command(label='Single')
sub_Edit_Layout.add_command(label='Two Columns')
sub_Edit_Layout.add_command(label='Three Columns')
sub_Edit_Layout.add_command(label='Two Rows')
sub_Edit_Layout.add_command(label='Three Rows')
sub_Edit_Layout.add_command(label='Grid(2x2)')
sub_Edit_Layout.add_command(label='Two Rows Right')
sub_Edit_Layout.add_command(label='Two Columns Bottom')
sub_Edit_Layout.add_separator()
sub_Edit_Layout.add_command(label='TWO Columns Bottom')
sub_Edit_Layout.add_separator()
sub_Edit_Layout.add_command(label='Flip Layout',accelerator='Shift+Alt+0')

view.add_separator()
view.add_command(label='Explorer',accelerator='Ctrl+Shift+E')
view.add_command(label='Search',accelerator='Ctrl+Shift+F')
view.add_command(label='SCM',accelerator='Ctrl+Shift+G')
view.add_command(label='Run',accelerator='Ctrl+Shift+D')
view.add_command(label='Extensions',accelerator='Ctrl+Shift+X')
view.add_command(label='Testing')
view.add_separator()
view.add_command(label='Problems',accelerator='Ctrl+Shift+M')
view.add_command(label='Output',accelerator='Ctrl+Shift+U')
view.add_command(label='Debug Console',accelerator='Ctrl+Shift+Y')
view.add_command(label='Terminal',accelerator='Ctrl+`')
view.add_separator()
view.add_command(label='Word Warp',accelerator='Ctrl+Z')
view.add_command(label='Show Minmap')
view.add_command(label='Show Breadcrumbs') 

#create go menu
go=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='Go', menu=go)
go.add_command(label='Back',accelerator='Alt+LeftArrow')
go.add_command(label='Forword',accelerator='Alt+RightArrow')
go.add_command(label='Last Edit Location',accelerator='Ctrl+K Ctrl+Q')
go.add_separator()

sub_go_Switch_Editor=Menu(go,tearoff=0)
go.add_cascade(label='Switch Editor',menu=sub_go_Switch_Editor)
sub_go_Switch_Editor.add_command(label='Next Editor',accelerator='Ctrl+PageDown')
sub_go_Switch_Editor.add_command(label='Previous Editor',accelerator='Ctrl+UpDown')
sub_go_Switch_Editor.add_separator()
sub_go_Switch_Editor.add_command(label='Next Used Editor')
sub_go_Switch_Editor.add_command(label='Previous Used Editor')
sub_go_Switch_Editor.add_separator()
sub_go_Switch_Editor.add_command(label='Next Editor in Group',accelerator='Ctrl+K Ctrl+PageDown')
sub_go_Switch_Editor.add_command(label='Previous Editor in Group',accelerator='Ctrl+K Ctrl+PageUp')
sub_go_Switch_Editor.add_separator()
sub_go_Switch_Editor.add_command(label='Next Used Editor in Group')
sub_go_Switch_Editor.add_command(label='Previous Used Editor in Group')

#creat sub menu for switch group
sub_go_Switch_Group=Menu(go,tearoff=0)
go.add_cascade(label='Switch Group',menu=sub_go_Switch_Group)
sub_go_Switch_Group.add_command(label='Group 1',accelerator='Ctrl+1')
sub_go_Switch_Group.add_command(label='Group 2',accelerator='Ctrl+2')
sub_go_Switch_Group.add_command(label='Group 3',accelerator='Ctrl+3')
sub_go_Switch_Group.add_command(label='Group 4',accelerator='Ctrl+4')
sub_go_Switch_Group.add_command(label='Group 5',accelerator='Ctrl+5')
sub_go_Switch_Group.add_separator()
sub_go_Switch_Group.add_command(label='Next Group')
sub_go_Switch_Group.add_command(label='Previous Group')
sub_go_Switch_Group.add_separator()
sub_go_Switch_Group.add_command(label='Group Left',accelerator='Ctrl+K Ctrl+LeftArrow')
sub_go_Switch_Group.add_command(label='Group Right',accelerator='Ctrl+K Ctrl+RightArrow')
sub_go_Switch_Group.add_command(label='Group Above',accelerator='Ctrl+K Ctrl+UpArrow')
sub_go_Switch_Group.add_command(label='Group Below',accelerator='Ctrl+K Ctrl+DownArrow')

go.add_separator()
go.add_command(label='Go to File...',accelerator='Ctrl+P')
go.add_command(label='Go to Symbol in Workshop',accelerator='Ctrl+T')
go.add_separator()
go.add_command(label='Go to Symbol in Editor... ',accelerator='Ctrl+Shift+O')
go.add_command(label='Go to Denifinition',accelerator='F12')
go.add_command(label='Go to Declaration')
go.add_command(label='Go to Type Definition')
go.add_command(label='Go to Implementations',accelerator='Ctrl+F12')
go.add_command(label='Go to References',accelerator='Shift+F12')
go.add_separator()
go.add_command(label='Go to Line/Column...',accelerator='Ctrl+G')
go.add_command(label='Go to Bracket',accelerator='Ctrl+Shift+\\')
go.add_separator()
go.add_command(label='Next Problem',accelerator='F8')
go.add_command(label='Previous Problem',accelerator='Shift+F8')
go.add_separator()
go.add_command(label='Next Change',accelerator='Alt+F3')
go.add_command(label='Previous Change',accelerator='Shift+Alt+F3')

#create run meunu
run=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='Run',menu=run)
run.add_command(label='Start Debugging',accelerator='F5')
run.add_command(label='Run Without Debugging',accelerator='Ctrl+F5')
run.add_command(label='Stop Debugging',accelerator='Shift+F5')
run.add_command(label='Restart Debugging',accelerator='Ctrl+Shift+F5')
run.add_separator()
run.add_command(label='Open Configurations')
run.add_command(label='Add Configurations')
run.add_separator()
run.add_command(label='Step Over',accelerator='F10')
run.add_command(label='Step Into',accelerator='F11')
run.add_command(label='Step Out',accelerator='Shift+F11')
run.add_command(label='Continue',accelerator='F5')
run.add_separator()
run.add_command(label='Toggle Breakpoint',accelerator='F9')
#add sub mebu for run new break point
sub_New_Breakpoint=Menu(run,tearoff=0)
run.add_cascade(label='New Breakpoint',menu=sub_New_Breakpoint)
sub_New_Breakpoint.add_command(label='Conditional Breakpoint...')
sub_New_Breakpoint.add_command(label='Inline Breakpoint',accelerator='Shift+F9')
sub_New_Breakpoint.add_command(label='Funcation Breakpoint...')
sub_New_Breakpoint.add_command(label='Logpoint...')
run.add_separator()
run.add_command(label='Enable All Breakpoint')
run.add_command(label='Disable All Breakpoint')
run.add_command(label='Remove All Breakpoint')
run.add_separator()
run.add_command(label='Install Additional Debuggers...')

#create new mterminal menu
terminal=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='Terminal',menu=terminal)
terminal.add_command(label='New Terminal',accelerator='Ctrl+Shift+`')
terminal.add_command(label='Split Terminal',accelerator='Ctrl+Shift+5')
terminal.add_separator()
terminal.add_command(label='Run Task...')
terminal.add_command(label='Run Build Task...',accelerator='Ctrl+Shift+B')
terminal.add_command(label='Run Active File')
terminal.add_command(label='Run Selected Text')
terminal.add_separator()
terminal.add_command(label='Show Runing Tasks...')
terminal.add_command(label='Restart Runing Tasks...')
terminal.add_command(label='Terminate Tasks...')
terminal.add_separator()
terminal.add_command(label='Configure Tasks...')
terminal.add_command(label='Configure Default Build Tasks...')

#create help menu 
helpp=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label='Help',menu=helpp)
helpp.add_command(label='Get Started',)
helpp.add_command(label='Show All Commands',accelerator='Ctrl+Shift+P')
helpp.add_command(label='Documentation')
helpp.add_command(label='Editor Playground')
helpp.add_command(label='Release Notes')
helpp.add_separator()
helpp.add_command(label='Keybord Shortcuts Reference',accelerator='Ctrl+K Ctrl+R')
helpp.add_command(label='Video Tutorials')
helpp.add_command(label='Tips and Tricks')
helpp.add_separator()
helpp.add_command(label='Join Us on Twitter')
helpp.add_command(label='Search Feature Requests')
helpp.add_command(label='Report Issue')
helpp.add_separator()
helpp.add_command(label='View License')
helpp.add_command(label='Privacy Statement')
helpp.add_separator()
helpp.add_command(label='Toggle Developer Tools',accelerator='Ctrl+Shift+I')
helpp.add_command(label='Open Process Explorer')
helpp.add_separator()
helpp.add_command(label='Check for Updates....')
helpp.add_separator()
helpp.add_command(label='About')


window.config(menu=menu_bar)
window.mainloop()
